### ISSUE TITLE
提取本地已安装apk

### ISSUE THREAD

**Issue by moter** [huclengyue/SmartUpdate#2]
在合并差分包的时候需要提取本地安装的apk。貌似这是需要root权限哦。

**Comment by appdev** [comment]
不需要，本地apk文件就在/data/app目录下。不许要root权限

**Comment by moter** [comment]
我取到的路径为空，你这个demo中的ndk需要单独编译吗？调用合并的时候自己app崩溃了，也没日志，貌似是native中出问题了

**Comment by appdev** [comment]
不需要  但是如果你是6.0以上版本。需要你手动给APP权限

**Comment by moter** [comment]
路径我用的：
ApplicationInfo applicationInfo = getApplicationContext().getApplicationInfo();
 String apkPath = applicationInfo.sourceDir;
现在是合成时出现新问题了  java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "signal" referenced by "libbsdiff.so"...
